# Generated by Django 5.2.7 on 2025-11-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_Name',
            new_name='company_name',
        ),
    ]
